import type { MapLayerConfig } from "@/types/map";
import { MapTool } from "@/hooks/useMapTools";
import {
  TOOL_CURSOR_MOVE,
  TOOL_CURSOR_MEASURE,
  TOOL_CURSOR_HEADING,
} from "@/utils/cursors";
import {
  RUNWAY_FILL_LAYER,
  RUNWAY_STROKE_LAYER,
  RUNWAY_CENTERLINE_LAYER,
  RUNWAY_LABEL_LAYER,
  TAXIWAY_FILL_LAYER,
  TAXIWAY_STROKE_LAYER,
  TAXIWAY_CENTERLINE_LAYER,
  TAXIWAY_LABEL_LAYER,
} from "./layers/surfaceLayers";
import {
  OBSTACLE_ICON_LAYER,
  OBSTACLE_BOUNDARY_LAYER,
  OBSTACLE_BOUNDARY_OUTLINE_LAYER,
  OBSTACLE_LABEL_LAYER,
  OBSTACLE_BUFFER_FILL_LAYER,
  OBSTACLE_BUFFER_OUTLINE_LAYER,
  SURFACE_BUFFER_FILL_LAYER,
  SURFACE_BUFFER_OUTLINE_LAYER,
} from "./layers/obstacleLayers";
import {
  SAFETY_ZONE_FILL_LAYER,
  SAFETY_ZONE_HATCH_LAYER,
  SAFETY_ZONE_BORDER_LAYER,
  SAFETY_ZONE_LABEL_LAYER,
  AIRPORT_BOUNDARY_LINE_LAYER,
} from "./layers/safetyZoneLayers";
import {
  AGL_POINT_LAYER,
  AGL_LABEL_LAYER,
  LHA_POINT_LAYER,
  LHA_LABEL_LAYER,
  EDGE_LIGHTS_LINE_LAYER,
} from "./layers/aglLayers";
import {
  getSimplifiedTrajectoryLayerIds,
  WAYPOINT_TRANSIT_CIRCLE_LAYER,
  WAYPOINT_MEASUREMENT_CIRCLE_LAYER,
  WAYPOINT_TAKEOFF_LAYER,
  WAYPOINT_LANDING_LAYER,
  WAYPOINT_HOVER_LAYER,
  WAYPOINT_RECORDING_BOOKEND_LAYER,
  WAYPOINT_LINE_LAYER,
  WAYPOINT_LABEL_LAYER,
  WAYPOINT_CAMERA_LINE_LAYER,
  WAYPOINT_ARROW_LAYER,
  WAYPOINT_CAMERA_TARGET_LAYER,
  WAYPOINT_WARNING_HIGHLIGHT_LAYER,
  WAYPOINT_INSPECTION_HIGHLIGHT_LAYER,
  WAYPOINT_SELECTED_LAYER,
  SIMPLIFIED_TAKEOFF_LAYER,
  SIMPLIFIED_LANDING_LAYER,
} from "./layers/waypointLayers";

// map layer id groups keyed by layer config key
export const layerGroupMap: Partial<Record<keyof MapLayerConfig, string[]>> = {
  simplifiedTrajectory: getSimplifiedTrajectoryLayerIds(),
  runways: [
    RUNWAY_FILL_LAYER,
    RUNWAY_STROKE_LAYER,
    RUNWAY_CENTERLINE_LAYER,
    RUNWAY_LABEL_LAYER,
  ],
  taxiways: [TAXIWAY_FILL_LAYER, TAXIWAY_STROKE_LAYER, TAXIWAY_CENTERLINE_LAYER, TAXIWAY_LABEL_LAYER],
  obstacles: [OBSTACLE_ICON_LAYER, OBSTACLE_BOUNDARY_LAYER, OBSTACLE_BOUNDARY_OUTLINE_LAYER, OBSTACLE_LABEL_LAYER],
  bufferZones: [OBSTACLE_BUFFER_FILL_LAYER, OBSTACLE_BUFFER_OUTLINE_LAYER, SURFACE_BUFFER_FILL_LAYER, SURFACE_BUFFER_OUTLINE_LAYER],
  safetyZones: [
    SAFETY_ZONE_FILL_LAYER,
    SAFETY_ZONE_HATCH_LAYER,
    SAFETY_ZONE_BORDER_LAYER,
    SAFETY_ZONE_LABEL_LAYER,
  ],
  airportBoundary: [AIRPORT_BOUNDARY_LINE_LAYER],
  aglSystems: [AGL_POINT_LAYER, AGL_LABEL_LAYER, LHA_POINT_LAYER, LHA_LABEL_LAYER, EDGE_LIGHTS_LINE_LAYER],
  transitWaypoints: [WAYPOINT_TRANSIT_CIRCLE_LAYER],
  measurementWaypoints: [
    WAYPOINT_MEASUREMENT_CIRCLE_LAYER,
    WAYPOINT_HOVER_LAYER,
    WAYPOINT_RECORDING_BOOKEND_LAYER,
    WAYPOINT_LABEL_LAYER,
  ],
  path: [WAYPOINT_LINE_LAYER],
  // simplified takeoff/landing markers belong to the `simplifiedTrajectory` group only -
  // listing them here too lets a takeoffLanding=false (forced by the simplified toggle
  // handler) overwrite the simplified group and hide the markers.
  takeoffLanding: [WAYPOINT_TAKEOFF_LAYER, WAYPOINT_LANDING_LAYER],
  cameraHeading: [WAYPOINT_CAMERA_LINE_LAYER, WAYPOINT_CAMERA_TARGET_LAYER],
  pathHeading: [WAYPOINT_ARROW_LAYER],
  trajectory: [
    WAYPOINT_WARNING_HIGHLIGHT_LAYER,
    WAYPOINT_INSPECTION_HIGHLIGHT_LAYER,
    WAYPOINT_SELECTED_LAYER,
  ],
};

// all interactive layer ids for click handling
export const INTERACTIVE_LAYERS = [
  RUNWAY_FILL_LAYER,
  TAXIWAY_FILL_LAYER,
  OBSTACLE_ICON_LAYER,
  OBSTACLE_BOUNDARY_LAYER,
  SAFETY_ZONE_FILL_LAYER,
  AIRPORT_BOUNDARY_LINE_LAYER,
  AGL_POINT_LAYER,
  LHA_POINT_LAYER,
];

// layers that show cursor pointer on hover
export const POINTER_LAYERS = [
  ...INTERACTIVE_LAYERS,
  WAYPOINT_TRANSIT_CIRCLE_LAYER,
  WAYPOINT_MEASUREMENT_CIRCLE_LAYER,
  WAYPOINT_TAKEOFF_LAYER,
  WAYPOINT_LANDING_LAYER,
  WAYPOINT_HOVER_LAYER,
  WAYPOINT_RECORDING_BOOKEND_LAYER,
  SIMPLIFIED_TAKEOFF_LAYER,
  SIMPLIFIED_LANDING_LAYER,
];

// cursor styles per active tool
export const TOOL_CURSORS: Record<string, string> = {
  [MapTool.SELECT]: "default",
  [MapTool.MOVE_WAYPOINT]: TOOL_CURSOR_MOVE,
  [MapTool.MOVE_FEATURE]: TOOL_CURSOR_MOVE,
  [MapTool.MEASURE]: TOOL_CURSOR_MEASURE,
  [MapTool.HEADING]: TOOL_CURSOR_HEADING,
  [MapTool.ZOOM]: "zoom-in",
  [MapTool.PLACE_TAKEOFF]: "crosshair",
  [MapTool.PLACE_LANDING]: "crosshair",
};
