"""initial schema

Revision ID: 86e6b78fad1a
Revises: 
Create Date: 2026-05-06 18:04:37.012946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drone_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('max_speed', sa.Float(), nullable=True),
    sa.Column('max_climb_rate', sa.Float(), nullable=True),
    sa.Column('max_altitude', sa.Float(), nullable=True),
    sa.Column('battery_capacity', sa.Float(), nullable=True),
    sa.Column('endurance_minutes', sa.Float(), nullable=True),
    sa.Column('camera_resolution', sa.String(), nullable=True),
    sa.Column('camera_frame_rate', sa.Integer(), nullable=True),
    sa.Column('sensor_fov', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('model_identifier', sa.String(), nullable=True),
    sa.Column('max_optical_zoom', sa.Float(), nullable=True),
    sa.Column('sensor_base_focal_length', sa.Float(), nullable=True),
    sa.Column('default_optical_zoom', sa.Float(), server_default='1.0', nullable=True),
    sa.Column('supports_geozone_upload', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('invitation_token', sa.String(), nullable=True),
    sa.Column('invitation_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("role IN ('OPERATOR', 'COORDINATOR', 'SUPER_ADMIN')", name='ck_users_role_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('airport',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('icao_code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('elevation', sa.Float(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('default_drone_profile_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('terrain_source', sa.String(length=20), nullable=False),
    sa.Column('dem_file_path', sa.String(), nullable=True),
    sa.CheckConstraint("terrain_source IN ('FLAT', 'DEM_UPLOAD', 'DEM_API')", name='ck_airport_terrain_source'),
    sa.ForeignKeyConstraint(['default_drone_profile_id'], ['drone_profile.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('icao_code')
    )
    op.create_table('camera_preset',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('drone_profile_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('white_balance', sa.String(length=20), nullable=True),
    sa.Column('iso', sa.Integer(), nullable=True),
    sa.Column('shutter_speed', sa.String(length=20), nullable=True),
    sa.Column('focus_mode', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['drone_profile_id'], ['drone_profile.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # at most one default preset per drone_profile bucket - mirrors
    # CameraPreset.__table_args__. raw SQL because the generic bucket uses
    # an expression index that op.create_index cannot render cleanly.
    op.execute(
        "CREATE UNIQUE INDEX uq_camera_preset_default_per_drone "
        "ON camera_preset (drone_profile_id) "
        "WHERE is_default = true AND drone_profile_id IS NOT NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_camera_preset_default_generic "
        "ON camera_preset ((drone_profile_id IS NULL)) "
        "WHERE is_default = true AND drone_profile_id IS NULL"
    )
    op.create_table('system_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('airfield_surface',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('airport_id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.String(length=10), nullable=False),
    sa.Column('surface_type', sa.String(length=20), nullable=False),
    sa.Column('geometry', sa.String(), nullable=False),
    sa.Column('boundary', sa.String(), nullable=True),
    sa.Column('buffer_distance', sa.Float(), nullable=False),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('threshold_position', sa.String(), nullable=True),
    sa.Column('end_position', sa.String(), nullable=True),
    sa.Column('touchpoint_latitude', sa.Float(), nullable=True),
    sa.Column('touchpoint_longitude', sa.Float(), nullable=True),
    sa.Column('touchpoint_altitude', sa.Float(), nullable=True),
    sa.Column('paired_surface_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("surface_type IN ('RUNWAY', 'TAXIWAY')", name='ck_airfield_surface_type'),
    sa.ForeignKeyConstraint(['airport_id'], ['airport.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paired_surface_id'], ['airfield_surface.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'ix_airfield_surface_paired_surface_id',
        'airfield_surface',
        ['paired_surface_id'],
        postgresql_where=sa.text('paired_surface_id IS NOT NULL'),
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('entity_name', sa.String(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('airport_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['airport_id'], ['airport.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_airport_id'), 'audit_log', ['airport_id'], unique=False)
    op.create_table('mission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('airport_id', sa.UUID(), nullable=False),
    sa.Column('operator_notes', sa.String(), nullable=True),
    sa.Column('drone_profile_id', sa.UUID(), nullable=True),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('default_speed', sa.Float(), nullable=True),
    sa.Column('measurement_speed_override', sa.Float(), nullable=True),
    sa.Column('default_altitude_offset', sa.Float(), nullable=True),
    sa.Column('takeoff_coordinate', sa.String(), nullable=True),
    sa.Column('landing_coordinate', sa.String(), nullable=True),
    sa.Column('default_capture_mode', sa.String(length=20), nullable=True),
    sa.Column('default_buffer_distance', sa.Float(), nullable=True),
    sa.Column('camera_mode', sa.String(length=10), server_default='AUTO', nullable=False),
    sa.Column('default_white_balance', sa.String(length=20), nullable=True),
    sa.Column('default_iso', sa.Integer(), nullable=True),
    sa.Column('default_shutter_speed', sa.String(length=20), nullable=True),
    sa.Column('default_focus_mode', sa.String(length=20), nullable=True),
    sa.Column('transit_agl', sa.Float(), nullable=True),
    sa.Column('require_perpendicular_runway_crossing', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('flight_plan_scope', sa.String(length=25), server_default='FULL', nullable=False),
    sa.Column('direction', sa.String(length=10), server_default='AUTO', nullable=False),
    sa.Column('has_unsaved_map_changes', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('computation_status', sa.String(length=20), server_default='IDLE', nullable=False),
    sa.Column('computation_error', sa.String(), nullable=True),
    sa.Column('computation_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("computation_status IN ('IDLE', 'COMPUTING', 'COMPLETED', 'FAILED')", name='ck_mission_computation_status'),
    sa.CheckConstraint("direction IN ('AUTO', 'NATURAL', 'REVERSED')", name='ck_mission_direction'),
    sa.CheckConstraint("flight_plan_scope IN ('FULL', 'NO_TAKEOFF_LANDING', 'MEASUREMENTS_ONLY')", name='ck_mission_flight_plan_scope'),
    sa.CheckConstraint("status IN ('DRAFT', 'PLANNED', 'VALIDATED', 'EXPORTED', 'COMPLETED', 'CANCELLED')", name='ck_mission_status'),
    sa.ForeignKeyConstraint(['airport_id'], ['airport.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drone_profile_id'], ['drone_profile.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obstacle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('airport_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('geometry', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('radius', sa.Float(), nullable=True),
    sa.Column('buffer_distance', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.CheckConstraint("type IN ('BUILDING', 'TOWER', 'ANTENNA', 'VEGETATION', 'OTHER')", name='ck_obstacle_type'),
    sa.ForeignKeyConstraint(['airport_id'], ['airport.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_zone',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('airport_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('geometry', sa.String(), nullable=False),
    sa.Column('altitude_floor', sa.Float(), nullable=True),
    sa.Column('altitude_ceiling', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("type IN ('CTR', 'RESTRICTED', 'PROHIBITED', 'TEMPORARY_NO_FLY', 'AIRPORT_BOUNDARY')", name='ck_safety_zone_type'),
    sa.ForeignKeyConstraint(['airport_id'], ['airport.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_airports',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('airport_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airport.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'airport_id')
    )
    op.create_table('agl',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('surface_id', sa.UUID(), nullable=False),
    sa.Column('agl_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=True),
    sa.Column('glide_slope_angle', sa.Float(), nullable=True),
    sa.Column('distance_from_threshold', sa.Float(), nullable=True),
    sa.Column('offset_from_centerline', sa.Float(), nullable=True),
    sa.CheckConstraint("agl_type IN ('PAPI', 'RUNWAY_EDGE_LIGHTS')", name='ck_agl_agl_type'),
    sa.ForeignKeyConstraint(['surface_id'], ['airfield_surface.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('constraint_rule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('constraint_type', sa.String(length=30), nullable=False),
    sa.Column('is_hard_constraint', sa.Boolean(), nullable=False),
    sa.Column('min_altitude', sa.Float(), nullable=True),
    sa.Column('max_altitude', sa.Float(), nullable=True),
    sa.Column('max_horizontal_speed', sa.Float(), nullable=True),
    sa.Column('max_vertical_speed', sa.Float(), nullable=True),
    sa.Column('max_flight_time', sa.Float(), nullable=True),
    sa.Column('reserve_margin', sa.Float(), nullable=True),
    sa.Column('lateral_buffer', sa.Float(), nullable=True),
    sa.Column('longitudinal_buffer', sa.Float(), nullable=True),
    sa.Column('boundary', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constraint_rule_mission_id'), 'constraint_rule', ['mission_id'], unique=False)
    op.create_table('flight_plan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('airport_id', sa.UUID(), nullable=False),
    sa.Column('total_distance', sa.Float(), nullable=True),
    sa.Column('estimated_duration', sa.Float(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['airport_id'], ['airport.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id')
    )
    op.create_table('export_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flight_plan_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('exported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("format IN ('MAVLINK', 'KML', 'KMZ', 'JSON', 'UGCS', 'WPML', 'CSV', 'GPX', 'LITCHI', 'DRONEDEPLOY')", name='ck_export_format'),
    sa.ForeignKeyConstraint(['flight_plan_id'], ['flight_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lha',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agl_id', sa.UUID(), nullable=False),
    sa.Column('unit_designator', sa.String(length=4), nullable=False),
    sa.Column('setting_angle', sa.Float(), nullable=True),
    sa.Column('transition_sector_width', sa.Float(), nullable=True),
    sa.Column('lamp_type', sa.String(length=10), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('tolerance', sa.Float(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.CheckConstraint("lamp_type IN ('HALOGEN', 'LED')", name='ck_lha_lamp_type'),
    sa.CheckConstraint('length(unit_designator) > 0', name='ck_lha_unit_designator'),
    sa.CheckConstraint('sequence_number > 0', name='ck_lha_sequence_positive'),
    sa.ForeignKeyConstraint(['agl_id'], ['agl.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agl_id', 'sequence_number', name='uq_lha_agl_sequence'),
    sa.UniqueConstraint('agl_id', 'unit_designator', name='uq_lha_agl_designator')
    )
    op.create_table('validation_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flight_plan_id', sa.UUID(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['flight_plan_id'], ['flight_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_plan_id')
    )
    op.create_table('inspection_configuration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('altitude_offset', sa.Float(), nullable=True),
    sa.Column('angle_offset_above', sa.Float(), nullable=True),
    sa.Column('angle_offset_below', sa.Float(), nullable=True),
    sa.Column('measurement_speed_override', sa.Float(), nullable=True),
    sa.Column('measurement_density', sa.Integer(), nullable=True),
    sa.Column('custom_tolerances', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('density', sa.Float(), nullable=True),
    sa.Column('hover_duration', sa.Float(), nullable=True),
    sa.Column('horizontal_distance', sa.Float(), nullable=True),
    sa.Column('sweep_angle', sa.Float(), nullable=True),
    sa.Column('angle_source', sa.String(length=10), nullable=True),
    sa.Column('angle_start', sa.Float(), nullable=True),
    sa.Column('angle_end', sa.Float(), nullable=True),
    sa.Column('lha_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lha_selection_rules', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('capture_mode', sa.String(length=20), nullable=True),
    sa.Column('recording_setup_duration', sa.Float(), nullable=True),
    sa.Column('buffer_distance', sa.Float(), nullable=True),
    sa.Column('height_above_lights', sa.Float(), nullable=True),
    sa.Column('lateral_offset', sa.Float(), nullable=True),
    sa.Column('distance_from_lha', sa.Float(), nullable=True),
    sa.Column('height_above_lha', sa.Float(), nullable=True),
    sa.Column('camera_gimbal_angle', sa.Float(), nullable=True),
    sa.Column('selected_lha_id', sa.UUID(), nullable=True),
    sa.Column('lha_setting_angle_override_id', sa.UUID(), nullable=True),
    sa.Column('hover_bearing', sa.Float(), nullable=True),
    sa.Column('hover_bearing_reference', sa.String(length=10), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('resolved_direction', sa.String(length=10), nullable=True),
    sa.Column('camera_preset_id', sa.UUID(), nullable=True),
    sa.Column('camera_mode', sa.String(length=10), nullable=True),
    sa.Column('white_balance', sa.String(length=20), nullable=True),
    sa.Column('iso', sa.Integer(), nullable=True),
    sa.Column('shutter_speed', sa.String(length=20), nullable=True),
    sa.Column('focus_mode', sa.String(length=20), nullable=True),
    sa.Column('optical_zoom', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['camera_preset_id'], ['camera_preset.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lha_setting_angle_override_id'], ['lha.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['selected_lha_id'], ['lha.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_configuration_lha_setting_angle_override_id'), 'inspection_configuration', ['lha_setting_angle_override_id'], unique=False)
    op.create_table('validation_violation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('validation_result_id', sa.UUID(), nullable=False),
    sa.Column('constraint_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('waypoint_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("category IN ('violation', 'warning', 'suggestion')", name='ck_validation_violation_category'),
    sa.ForeignKeyConstraint(['constraint_id'], ['constraint_rule.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['validation_result_id'], ['validation_result.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection_template',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('default_config_id', sa.UUID(), nullable=True),
    sa.Column('angular_tolerances', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['default_config_id'], ['inspection_configuration.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insp_template_methods',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['inspection_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id', 'method')
    )
    op.create_table('insp_template_targets',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('agl_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agl_id'], ['agl.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['inspection_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id', 'agl_id')
    )
    op.create_table('inspection',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('config_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['inspection_configuration.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['inspection_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waypoint',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flight_plan_id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('hover_duration', sa.Float(), nullable=True),
    sa.Column('camera_action', sa.String(length=20), nullable=True),
    sa.Column('waypoint_type', sa.String(length=20), nullable=False),
    sa.Column('camera_target', sa.String(), nullable=True),
    sa.Column('gimbal_pitch', sa.Float(), nullable=True),
    sa.CheckConstraint("camera_action IN ('NONE', 'PHOTO_CAPTURE', 'RECORDING_START', 'RECORDING', 'RECORDING_STOP')", name='ck_waypoint_camera_action'),
    sa.CheckConstraint("waypoint_type IN ('TAKEOFF', 'TRANSIT', 'MEASUREMENT', 'HOVER', 'LANDING')", name='ck_waypoint_type'),
    sa.ForeignKeyConstraint(['flight_plan_id'], ['flight_plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waypoint')
    op.drop_table('inspection')
    op.drop_table('insp_template_targets')
    op.drop_table('insp_template_methods')
    op.drop_table('inspection_template')
    op.drop_table('validation_violation')
    op.drop_index(op.f('ix_inspection_configuration_lha_setting_angle_override_id'), table_name='inspection_configuration')
    op.drop_table('inspection_configuration')
    op.drop_table('validation_result')
    op.drop_table('lha')
    op.drop_table('export_result')
    op.drop_table('flight_plan')
    op.drop_index(op.f('ix_constraint_rule_mission_id'), table_name='constraint_rule')
    op.drop_table('constraint_rule')
    op.drop_table('agl')
    op.drop_table('user_airports')
    op.drop_table('safety_zone')
    op.drop_table('obstacle')
    op.drop_table('mission')
    op.drop_index(op.f('ix_audit_log_airport_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_airfield_surface_paired_surface_id', table_name='airfield_surface')
    op.drop_table('airfield_surface')
    op.drop_table('system_settings')
    op.execute("DROP INDEX IF EXISTS uq_camera_preset_default_generic")
    op.execute("DROP INDEX IF EXISTS uq_camera_preset_default_per_drone")
    op.drop_table('camera_preset')
    op.drop_table('airport')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('drone_profile')
    # ### end Alembic commands ###
